# -- DEV DOCKER-COMPOSE --
# -- DO NOT USE IN PRODUCTION! --

version: "3"
services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ..:/app
      - ~/.gitconfig:/etc/gitconfig
